version: '2'
services:
 scheduler:
  depends_on:
   - db
  image: redisforlosers/lpl_scheduler
  volumes:
   - ./:/var/www/html/
  ports:
   - 80:80
  container_name: scheduler

 phpmyadmin:
  depends_on:
   - db
  image: phpmyadmin/phpmyadmin
  ports:
   - 8080:80
  container_name: phpmyadmin-scheduler

 db:
  image: mysql:5.7
  volumes:
   - ./db/:/docker-entrypoint-initdb.d
  restart: always
  environment:
   MYSQL_RANDOM_ROOT_PASSWORD: 1
   MYSQL_DATABASE: dev_scheduler
   MYSQL_PASSWORD: hqJfb4XOQdWhITWR
   MYSQL_USER: lpl_scheduler
  ports:
   - 3306:3306
  container_name: mysql-scheduler